spring:
  # sa-token配置
  sa-token:
    # token名称 (同时也是cookie名称)
    token-name: authorization
    # token有效期，单位s 默认30天, -1代表永不过期
    timeout: 43200
    # token临时有效期 (指定时间内无操作就视为token过期) 单位: 秒
    activity-timeout: -1
    # 是否允许同一账号并发登录 (为true时允许一起登录, 为false时新登录挤掉旧登录)
    allow-concurrent-login: true
    # 在多人登录同一账号时，是否共用一个token (为true时所有登录共用一个token, 为false时每次登录新建一个token)
    is-share: true
    # token风格(默认可取值：uuid、simple-uuid、random-32、random-64、random-128、tik)
    token-style: uuid
    # 是否尝试从header里读取token
    is-read-head: true
    # 是否显示banner
    is-v: false
    # 打印日志
    is-log: false